# ./test.sh :Run all the tests.
# ./test.sh -g 1 :Run only general tests
# ./test.sh -e 1 :Run only end to end tests for all the suits in test/endToEnd
# ./test.sh -e 1 -f "suiteName" :Run only end to end tests for a specific suit

# todo- Add this to generate.sh
export CHPL_MODULE_PATH=$PWD/src

while getopts ":g:e:f:" opt; do
  case $opt in
    g) generalTests="$OPTARG"
    ;;
    e) endToEndTests="$OPTARG"
    ;;
    f) specificSuit="$OPTARG"
    ;;
    \?) echo "Invalid argument -$OPTARG" >&2
    ;;
  esac
done

endToEnd() {

  echo "Running for $1"

  dir=test/endToEnd/$1
  protoc --chpl_out=$dir $dir/protoFile/$1.proto
  protoc -I=$dir/protoFile/ --python_out=$dir $dir/protoFile/$1.proto

  #write from chapel and read from chapel
  echo "Chapel to chapel"
  chpl -o $dir/write $dir/write.chpl
  $dir/./write
  chpl -o $dir/read $dir/read.chpl
  OUTPUT="$($dir/./read)"
  rm -r $dir/write
  rm -r $dir/read
  rm -r out
  if echo $OUTPUT | grep -q 'false'; then
    echo "tests failed for chapel to chapel"
    exit 1
  else
    echo "chapel to chapel passed"
    echo "=======================" 
  fi

  #write from chapel and read from python
  echo "chapel to python"
  chpl -o $dir/write $dir/write.chpl
  $dir/./write
  OUTPUT="$(python3 $dir/read.py)"
  rm -r $dir/write
  rm -r out
  if echo $OUTPUT | grep -q 'false'; then
    echo "tests failed for chapel to python"
    exit 1
  else
    echo "chapel to python passed"
    echo "=======================" 
  fi

  #write from python and read from chapel
  echo "python to chapel"
  python3 $dir/write.py
  chpl -o $dir/read $dir/read.chpl
  OUTPUT="$($dir/./read)"
  rm -r $dir/read
  rm -r out
  if echo $OUTPUT | grep -q 'false'; then
    echo "tests failed for python to chapel"
    exit 1
  else
    echo "python to chapel passed"
    echo "=======================" 
  fi

  #remove files generated by protoc
  rm -r $dir/$1*
}

if [ -z "$endToEndTests" ]; then
  echo "running general tests "

  OUTPUT="$(start_test test/general)"
  if echo $OUTPUT | grep -q '#Failures = 0'; then
    echo "All general tests passed."
    echo "======================="
  else
    echo "general tests failed"
    exit 1
  fi

fi

if [ -z "$generalTests" ]; then 
  echo "running end to end tests"

  if [ ! -z "$specificSuit" ]; then
    endToEnd $specificSuit
  else
    for suite in "test/endToEnd"/*
    do
      endToEnd $(basename $suite)
    done
  fi

fi
